package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String customerStatus;
	private java.lang.Float totalFraudAmount;

	private boolean automated;

	public FraudData() {
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public java.lang.Float getTotalFraudAmount() {
		return this.totalFraudAmount;
	}

	public void setTotalFraudAmount(java.lang.Float totalFraudAmount) {
		this.totalFraudAmount = totalFraudAmount;
	}

	public boolean isAutomated() {
		return this.automated;
	}

	public void setAutomated(boolean automated) {
		this.automated = automated;
	}

	public FraudData(java.lang.String customerStatus,
			java.lang.Float totalFraudAmount, boolean automated) {
		this.customerStatus = customerStatus;
		this.totalFraudAmount = totalFraudAmount;
		this.automated = automated;
	}

}