package com.fsi_credit_dispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalInformation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AdditionalInformation() {
    }




}