package com.fsi_credit_dispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Question ID")
	private java.lang.Integer questionId;
	@org.kie.api.definition.type.Label("Answer Value")
	private java.lang.String answerValue;

	@org.kie.api.definition.type.Label(value = "Question Type")
	private java.lang.String questionType;

	public AdditionalInformation() {
	}

	public java.lang.Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(java.lang.Integer questionId) {
		this.questionId = questionId;
	}

	public java.lang.String getAnswerValue() {
		return this.answerValue;
	}

	public void setAnswerValue(java.lang.String answerValue) {
		this.answerValue = answerValue;
	}

	public java.lang.String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(java.lang.String questionType) {
		this.questionType = questionType;
	}

	public AdditionalInformation(java.lang.Integer questionId,
			java.lang.String answerValue, java.lang.String questionType) {
		this.questionId = questionId;
		this.answerValue = answerValue;
		this.questionType = questionType;
	}

}