package com.fsi_credit_dispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cardholder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("State Code")
	private java.lang.String stateCode;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Cardholder Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label(value = "Incident Count (last 3 years)")
	private java.lang.Integer incidentCount;

	public Cardholder() {
	}

	public java.lang.String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(java.lang.String stateCode) {
		this.stateCode = stateCode;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getIncidentCount() {
		return this.incidentCount;
	}

	public void setIncidentCount(java.lang.Integer incidentCount) {
		this.incidentCount = incidentCount;
	}

	public Cardholder(java.lang.String stateCode, java.lang.Integer age,
			java.lang.String status, java.lang.Integer incidentCount) {
		this.stateCode = stateCode;
		this.age = age;
		this.status = status;
		this.incidentCount = incidentCount;
	}

}