package com.fsi.creditcarddisputecase;

rule "Get county name"
    ruleflow-group "additional-info"
when Cardholder( stateCode == "VA" )
then
    AdditionalInformation additionalInfo = new AdditionalInformation();
    additionalInfo.setQuestionId(1);
    additionalInfo.setQuestionPrompt("What county do you reside in?");
    additionalInfo.setQuestionType("string");
    insert (additionalInfo);
end;