package com.fsi_credit_dispute;

import com.fsi_credit_dispute.AdditionalInformation;
import com.fsi_credit_dispute.Cardholder;

rule "Get county name"
    agenda-group "additional-info"
when Cardholder( state == "VA" )
then
    AdditionalInfo additionalInfo = new AdditionalInfo();
    additionalInfo.setQuestionId(1);
    additionalInfo.setQuestionPrompt("What county do you reside in?");
    additionalInfo.setQuestionType("string");
    insert (additionalInfo);
end;