package com.fsi.creditcarddisputecase;

rule "Additional info check"
    agenda-group "additional-info"
when

then
    System.out.println("Looking for additional info!");
end;

rule "Online purchases DC Area by minor"
    agenda-group "additional-info"
when Cardholder( stateCode in ("VA","DC","MD") )
then
    AdditionalInformation additionalInfo = new AdditionalInformation();
    additionalInfo.setQuestionId(1);
    additionalInfo.setQuestionPrompt("Were any charges related to online purchases?");
    additionalInfo.setQuestionType("boolean");
    insert (additionalInfo);
end;

rule "New York travel rule for Gold level cardholders"
    agenda-group "additional-info"
when Cardholder ( stateCode == "NY", status == "GOLD" )
then
    AdditionalInformation additionalInfo = new AdditionalInformation();
    additionalInfo.setQuestionId(2);
    additionalInfo.setQuestionPrompt("Were you on travel when the disputed charges occurred?");
    additionalInfo.setQuestionType("boolean");
    insert (additionalInfo);
end;


query "get-additional-info"
    additionalInfo : AdditionalInformation()
end;

rule "Cleanup additional info"
    agenda-group "cleanup"
when
    $additionalInfo : AdditionalInformation()
then
    retract($additionalInfo);
end;

rule "Cleanup cardholder"
    agenda-group "cleanup"
when
    $cardholder : Cardholder()
then
    retract($cardholder);
end;
