package com.fsi.creditcarddisputecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Line Item Count")
	private java.lang.Integer lineItemCount;
	@org.kie.api.definition.type.Label("Oldest Disputed Charge (days)")
	private java.lang.Integer maxDaysElapsed;

	@org.kie.api.definition.type.Label("Total Fraud Amount")
	private java.lang.Float totalFraudAmount;

	@org.kie.api.definition.type.Label("Automated")
	private boolean automated;

	@org.kie.api.definition.type.Label("Customer Status")
	private java.lang.String customerStatus;

	public FraudData() {
	}

	public java.lang.Integer getLineItemCount() {
		return this.lineItemCount;
	}

	public void setLineItemCount(java.lang.Integer lineItemCount) {
		this.lineItemCount = lineItemCount;
	}

	public java.lang.Integer getMaxDaysElapsed() {
		return this.maxDaysElapsed;
	}

	public void setMaxDaysElapsed(java.lang.Integer maxDaysElapsed) {
		this.maxDaysElapsed = maxDaysElapsed;
	}

	public FraudData(
			java.lang.Double totalDisputeAmount,
			java.lang.Integer lineItemCount,
			java.lang.Integer maxDaysElapsed) {
		this.totalDisputeAmount = totalDisputeAmount;
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
	}

	public java.lang.Float getTotalFraudAmount() {
		return this.totalFraudAmount;
	}

	public void setTotalFraudAmount(java.lang.Float totalFraudAmount) {
		this.totalFraudAmount = totalFraudAmount;
	}

	public boolean isAutomated() {
		return this.automated;
	}

	public void setAutomated(boolean automated) {
		this.automated = automated;
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public FraudData(java.lang.Integer lineItemCount,
			java.lang.Integer maxDaysElapsed, java.lang.Float totalFraudAmount,
			boolean automated, java.lang.String customerStatus) {
		this.lineItemCount = lineItemCount;
		this.maxDaysElapsed = maxDaysElapsed;
		this.totalFraudAmount = totalFraudAmount;
		this.automated = automated;
		this.customerStatus = customerStatus;
	}

}